### ISSUE TITLE
[ Section2/ Lecture 21/  00:59] The video was cut

### ISSUE THREAD

**Issue by abdennour** [jleetutorial/kubernetes-demo#12]
The instructor said "to determine when a pod is healthy or unhealthy" but he didn't complete the second part of the phrase which is "after it has become ready"

**Lecture**

 https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9630316

**Related questions**

- https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9630316

**Comment by jleetutorial** [comment]
Now fixed: https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9630316?start=0
