### ISSUE TITLE
[ Section2. Lecture 21 ] Request more hands-on with healthchecks

### ISSUE THREAD

**Issue by abdennour** [jleetutorial/kubernetes-demo#13]
This is a request of adding hands-on lectures about healthchecks
**Lecture**

- https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9630316

**Related question**

https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9630316

**Comment by jleetutorial** [comment]
Now fixed: https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9630316?start=0
