### ISSUE TITLE
[Section1, L3 ] Add a guide on how to pull changes after moving repository to LevelUp account

### ISSUE THREAD

**Issue by abdennour** [jleetutorial/kubernetes-demo#22]
# Overview

This lecture needs update namely after moving the GH repository to LevelUpEducation GH account

# Related Lecture

https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9624364?start=0

# Related Question:

https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9624364?start=0

**Comment by jleetutorial** [comment]
@abdennour Thanks for reporting this.
I have updated the lecture as suggested.

But I don't think we need to update the remote of the git repo.

git will automatically redirect to https://github.com/LevelUpEducation/kubernetes-demo.git even if you run `git pull` in a already cloned repo.
